#!/usr/bin/env python3
import requests
import json
import base64

# Decode the encrypted token
encrypted = 'eyJpdiI6IklSektLbUdvRkRvSyswTnpTZHlUblE9PSIsInZhbHVlIjoiekl4TkJjTFZKaStFK0FOSnpOWTI3MWJhYzVRNnNka2NOY2o0L0NpK3R2enkwZFl1OU5PSG5IYmZXOW9oRW9iUWpyL2FuNmZoOVBrRFNlZHVEWW9QaVRMYjFiMGpJNjRwdWtOekFWcGIvdmU2MjVpS1VkRmljYW82Sy9DcFhmY1VrdzIrZGU2b3kzN1R0THhIR3p2UUpHTmJpd2JvN0xPMTRDY0RoT1BPa1kzeE90eWt1M1VlTGVNUzhWUlNMaGVSUWdIM1BkYmtUVmZnb3dZWGF3bU11S1dPMFhSZUhBTlBCRnJFRGpkbldiNXdhUSt0YnJvZlllc0tnbmFqNTB4NGQvUjhZY2RISWtpeS9MaHFFdWVmb0NVbC8veUtCU1I2aUdtSFM5eS9QVnJxS1ErTzNXTERJSTdhbForZHh4RXJDUzJOcG9OV1pxdjJQLzF2VFVrOUk4dVJHT2R3RjRXL0RYN1NHWi95V2FkMlN5M2tlMk13cjdyUjE5eGZadHZPY3VIejhMTTNXZXQ0U2dpbmFvc0RJdWRZZGpYT1VhV2I0MGhvZmZibnZoR2ZuZzVtQmduZlE2UFJLOFk0NEFNa2lFbFFWUVhWZEZaMUdXU1JremUzdXc9PSIsIm1hYyI6IjE4MGIwMWI3ZDQzZTI4MzMxNDVmYmUyY2E1ZjExYzZkYjYzNzRmZWExNjM4YTg5YzBhZjY3NTA3YmNiN2M1ZTIiLCJ0YWciOiIifQ=='

data = json.loads(base64.b64decode(encrypted))

# The actual token is encrypted, but we need to decrypt it
# For now, let's try to use the decrypted value directly
# Note: This is a placeholder - we need the actual decrypted token

# The encrypted data suggests this is Laravel's encryption format
# We would need the APP_KEY to decrypt it

print('This token is encrypted and requires decryption with the APP_KEY')
print('Please provide the decrypted access token or the APP_KEY')
