"""Editorial decision layer (Phase 1) — dormant until the cadence cutover.

Sits between the existing feed intelligence (agent/feed_authority.py,
agent/feed_clustering.py, agent/feed_opportunity.py) and the existing
publishers. Composes them; does not replace them.

Stage 1 — feature flag, slot config loader, twelve editorial formats.
Stage 2 — source-confidence scoring.
Stage 2.5 — candidate normalization adapter.
Stage 2.6 — source relationships.
Stage 3 — deterministic saturation prevention.
Stage 3.5 — publication metadata contract.
Stage 4 — deterministic admission and backup-candidate selection.
Stage 5 — deterministic editorial-quality scoring.
Stage 6 — deterministic publication readiness verdict.
Stage 7A — deterministic artifact builders (brief, trend, report).

Nothing here runs in production while EDITORIAL_SLOTS_ENABLED is false, and the
editorial formats are structurally isolated from the live rotation registries
regardless of that flag — see tests/test_editorial_dormancy.py.
"""
from .flags import (
    editorial_shadow_mode,
    editorial_slots_enabled,
    editorial_timezone,
    editorial_zoneinfo,
)
from .candidate_adapter import (
    NormalizationConfig,
    NormalizationConfigError,
    load_normalization_config,
    normalize_and_score,
    normalize_candidate,
    normalize_many,
)
from .models import (
    DEVELOPMENT_TYPES,
    NormalizationError,
)
from .slots import (
    ContentType,
    Slot,
    SlotConfig,
    SlotConfigError,
    load_slots,
)
from .publication_record import (
    PUBLICATION_METADATA_VERSION,
    PublicationMetadataError,
    backfill_metadata,
    build_publication_metadata,
    record_publication,
    validate_publication_metadata,
)
from .saturation import (
    ContinuationClaim,
    HistoryView,
    PublicationRecord,
    SaturationConfig,
    SaturationConfigError,
    SaturationResult,
    build_history,
    evaluate_saturation,
    load_history,
    load_saturation_config,
    relationship_observability,
)
from .admission import (
    ALL_REASON_CODES,
    ADMITTED,
    AdmissionResult,
    CandidateEvaluation,
    REASON_EXPLANATIONS,
    REJECTED,
    RC_ARTIFACT_NOT_ALLOWED,
    RC_ARTIFACT_REPETITION,
    RC_CANDIDATE_LIMIT_REACHED,
    RC_DEVELOPMENT_TYPE_NOT_ALLOWED,
    RC_ENTITY_DEVELOPMENT_SATURATED,
    RC_ENTITY_SATURATED,
    RC_EXACT_TOPIC_DUPLICATE,
    RC_INSUFFICIENT_CORROBORATION,
    RC_INVALID_CANDIDATE,
    RC_MISSING_REQUIRED_CLAIM_EVIDENCE,
    RC_NO_CANDIDATE_PASSED,
    RC_OPPORTUNITY_SCORE_BELOW_THRESHOLD,
    RC_PRACTICAL_VALUE_MISSING,
    RC_PRIMARY_SOURCE_REQUIRED,
    RC_SAME_DAY_REUSE,
    RC_SOURCE_CONFIDENCE_BELOW_THRESHOLD,
    RC_THEME_SATURATED,
    SKIPPED_NO_CANDIDATE,
    SlotPolicy,
    SlotPolicyError,
    WARNING,
    admit_to_slot,
    assess_practical_value,
    build_slot_policy,
    evaluate_and_record,
    evaluate_candidate,
    record_shadow_decision,
)
from .source_relationships import (
    RelationshipConfig,
    RelationshipConfigError,
    SourceRelationship,
    analyze_candidate,
    apply_relationships,
    detect_relationships,
    load_relationship_config,
    resolve_organization,
)
from .source_confidence import (
    Candidate,
    Claim,
    Component,
    ScoringConfig,
    ScoringConfigError,
    SourceConfidence,
    SourceRef,
    load_scoring_config,
    registrable_domain,
    score_source_confidence,
)
from .quality import (
    DraftInput,
    QualityResult,
    evaluate_quality,
)
from .readiness import (
    STATUS_READY,
    STATUS_READY_WITH_WARNINGS,
    STATUS_REJECTED,
    STATUS_REQUIRES_MANUAL_REVIEW,
    ReadinessConfig,
    ReadinessConfigError,
    ReadinessInput,
    ReadinessDecision,
    evaluate_readiness,
    evaluate_and_record_readiness,
    load_readiness_config,
    record_readiness_decision,
)
from .artifacts import (
    Artifact,
    ArtifactOverlapError,
    BriefCandidate,
    BriefClaim,
    BriefSource,
    DailyBriefInput,
    QualityBreakdown,
    SourceConfidenceBreakdown,
    WeeklyReportInput,
    WeeklyTrendInput,
    build_intelligence_brief,
    build_weekly_intelligence_report,
    build_weekly_trend_analysis,
    save_artifact,
    validate_artifact_distinctness,
)
from .orchestrator import (
    ALLOWED_MODES,
    MODE_REPLAY,
    MODE_SHADOW,
    OUTCOME_DRAFT_GENERATION_FAILED,
    OUTCOME_INVALID_CONFIGURATION,
    OUTCOME_PIPELINE_FAILED,
    OUTCOME_QUALITY_REJECTED,
    OUTCOME_READY_IN_SHADOW,
    OUTCOME_READY_WITH_WARNINGS_HOLD,
    OUTCOME_REQUIRES_MANUAL_REVIEW,
    OUTCOME_SKIPPED_NO_CANDIDATE,
    PipelineInput,
    PipelineResult,
    SlotResult,
    run_pipeline,
)
from .replay import (
    DayReplayResult,
    WeeklyReplayInput,
    WeeklyReplayResult,
    run_weekly_replay,
)

__all__ = [
    "DEVELOPMENT_TYPES",
    "Candidate",
    "Claim",
    "Component",
    "ContentType",
    "NormalizationConfig",
    "NormalizationConfigError",
    "NormalizationError",
    "PUBLICATION_METADATA_VERSION",
    "PublicationMetadataError",
    "backfill_metadata",
    "build_publication_metadata",
    "record_publication",
    "validate_publication_metadata",
    "ContinuationClaim",
    "HistoryView",
    "PublicationRecord",
    "SaturationConfig",
    "SaturationConfigError",
    "SaturationResult",
    "build_history",
    "evaluate_saturation",
    "load_history",
    "load_saturation_config",
    "relationship_observability",
    "RelationshipConfig",
    "RelationshipConfigError",
    "SourceRelationship",
    "analyze_candidate",
    "apply_relationships",
    "detect_relationships",
    "load_relationship_config",
    "resolve_organization",
    "load_normalization_config",
    "normalize_and_score",
    "normalize_candidate",
    "normalize_many",
    "ScoringConfig",
    "ScoringConfigError",
    "Slot",
    "SlotConfig",
    "SlotConfigError",
    "SourceConfidence",
    "SourceRef",
    "editorial_shadow_mode",
    "editorial_slots_enabled",
    "editorial_timezone",
    "editorial_zoneinfo",
    "load_scoring_config",
    "load_slots",
    "registrable_domain",
    "score_source_confidence",
    # Stage 4 — admission
    "ADMITTED",
    "REJECTED",
    "WARNING",
    "INVALID_CANDIDATE",
    "SKIPPED_NO_CANDIDATE",
    "ALL_REASON_CODES",
    "REASON_EXPLANATIONS",
    "RC_INVALID_CANDIDATE",
    "RC_SOURCE_CONFIDENCE_BELOW_THRESHOLD",
    "RC_PRIMARY_SOURCE_REQUIRED",
    "RC_INSUFFICIENT_CORROBORATION",
    "RC_OPPORTUNITY_SCORE_BELOW_THRESHOLD",
    "RC_EXACT_TOPIC_DUPLICATE",
    "RC_ENTITY_SATURATED",
    "RC_ENTITY_DEVELOPMENT_SATURATED",
    "RC_THEME_SATURATED",
    "RC_SAME_DAY_REUSE",
    "RC_ARTIFACT_REPETITION",
    "RC_DEVELOPMENT_TYPE_NOT_ALLOWED",
    "RC_ARTIFACT_NOT_ALLOWED",
    "RC_PRACTICAL_VALUE_MISSING",
    "RC_MISSING_REQUIRED_CLAIM_EVIDENCE",
    "RC_CANDIDATE_LIMIT_REACHED",
    "RC_NO_CANDIDATE_PASSED",
    "AdmissionResult",
    "CandidateEvaluation",
    "SlotPolicy",
    "SlotPolicyError",
    "admit_to_slot",
    "assess_practical_value",
    "build_slot_policy",
    "evaluate_and_record",
    "evaluate_candidate",
    "record_shadow_decision",
    # Stage 5 — quality scoring
    "DraftInput",
    "QualityResult",
    "evaluate_quality",
    # Stage 6 — readiness verdict
    "STATUS_READY",
    "STATUS_READY_WITH_WARNINGS",
    "STATUS_REJECTED",
    "STATUS_REQUIRES_MANUAL_REVIEW",
    "ReadinessConfig",
    "ReadinessConfigError",
    "ReadinessInput",
    "ReadinessDecision",
    "evaluate_readiness",
    "evaluate_and_record_readiness",
    "load_readiness_config",
    "record_readiness_decision",
    # Stage 7A — deterministic artifact builders
    "Artifact",
    "ArtifactOverlapError",
    "BriefCandidate",
    "BriefClaim",
    "BriefSource",
    "DailyBriefInput",
    "QualityBreakdown",
    "SourceConfidenceBreakdown",
    "WeeklyReportInput",
    "WeeklyTrendInput",
    "build_intelligence_brief",
    "build_weekly_intelligence_report",
    "build_weekly_trend_analysis",
    "save_artifact",
    "validate_artifact_distinctness",
    # Stage 7B — dormant end-to-end orchestrator
    "ALLOWED_MODES",
    "MODE_REPLAY",
    "MODE_SHADOW",
    "OUTCOME_DRAFT_GENERATION_FAILED",
    "OUTCOME_INVALID_CONFIGURATION",
    "OUTCOME_PIPELINE_FAILED",
    "OUTCOME_QUALITY_REJECTED",
    "OUTCOME_READY_IN_SHADOW",
    "OUTCOME_READY_WITH_WARNINGS_HOLD",
    "OUTCOME_REQUIRES_MANUAL_REVIEW",
    "OUTCOME_SKIPPED_NO_CANDIDATE",
    "PipelineInput",
    "PipelineResult",
    "SlotResult",
    "run_pipeline",
    # Stage 7C — historical replay
    "DayReplayResult",
    "WeeklyReplayInput",
    "WeeklyReplayResult",
    "run_weekly_replay",
]
