"""Brand-DNA learning: build a brand profile by reading the buyer's site.

`smkit learn https://yoursite.com` fetches the page(s), asks the configured
LLM to infer voice/audience/topics, and writes a ready-to-use brand profile
(`config/profiles/<name>.yaml`). This is the "ingest my site to learn my
brand" capability buyers expect — no manual profile authoring.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

from .config import PROFILES_DIR, ROOT, AgentConfig
from .llm import LLMClient, LLMError

sys.path.insert(0, str(ROOT / "scripts"))

SYSTEM = """You are a brand strategist. Given raw text scraped from a brand's \
website/blog, infer its content brand profile. Respond with ONLY a JSON object \
(no prose, no code fences) with these keys:
- name: the brand or author name (string)
- tone: a one-line description of the writing voice (string)
- audience: who they write for (string)
- language: primary language (string, e.g. "English")
- cta: a natural call-to-action they'd use (string)
- hashtags: 2-5 relevant hashtags (array of strings, each starting with #)
- topics: 3-6 core topics/themes they cover (array of strings)
Base everything on evidence in the text. Do not invent a brand name if unclear \
— use a sensible placeholder."""


def _extract_json(text: str) -> dict:
    text = text.strip()
    text = re.sub(r"^```(?:json)?|```$", "", text, flags=re.MULTILINE).strip()
    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end != -1:
        text = text[start : end + 1]
    return json.loads(text)


def learn_brand(
    url: str,
    profile_name: str = "default",
    platforms: list[str] | None = None,
    config: AgentConfig | None = None,
) -> tuple[bool, str]:
    """Infer a brand profile from a URL and write it. Returns (ok, message)."""
    import content_research

    config = config or AgentConfig.load()
    text = content_research.extract_article(url, max_chars=8000)
    if not text or text.startswith("[Extraction failed"):
        return False, f"Could not read {url}: {text[:120]}"

    try:
        client = LLMClient(
            provider=config.provider, model=config.model, api_key=config.api_key,
            base_url=config.base_url, max_tokens=1024, temperature=0.2,
        )
        resp = client.complete(
            SYSTEM,
            [{"role": "user", "content": [{"type": "text", "text":
                f"Source: {url}\n\nText:\n{text}"}]}],
        )
    except LLMError as exc:
        return False, str(exc)

    try:
        data = _extract_json(resp.text)
    except (json.JSONDecodeError, ValueError):
        return False, f"Model did not return valid JSON. Got:\n{resp.text[:300]}"

    profile = {
        "name": data.get("name", "My Brand"),
        "tone": data.get("tone", "clear and professional"),
        "audience": data.get("audience", "a general audience"),
        "language": data.get("language", "English"),
        "cta": data.get("cta", ""),
        "link": url,
        "hashtags": data.get("hashtags", []) or [],
        "topics": data.get("topics", []) or [],
        "platforms": platforms or ["blog", "x", "linkedin"],
        "branding": {"bg_color": "#0f172a", "accent_color": "#2563eb"},
        "blog": {"category_id": None, "tags": []},
    }

    PROFILES_DIR.mkdir(parents=True, exist_ok=True)
    path = PROFILES_DIR / f"{profile_name}.yaml"
    path.write_text(
        "# Generated by `smkit learn` — review and tweak.\n"
        + yaml.safe_dump(profile, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return True, str(path)
